---
apiVersion: v1
kind: Service
metadata:
  name: nginx-errors
  labels:
    app.kubernetes.io/name: nginx-errors
    app.kubernetes.io/part-of: ingress-nginx
spec:
  selector:
    app.kubernetes.io/name: nginx-errors
    app.kubernetes.io/part-of: ingress-nginx
  ports:
  - port: 80
    targetPort: 8080
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-errors
  labels:
    app.kubernetes.io/name: nginx-errors
    app.kubernetes.io/part-of: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-errors
      app.kubernetes.io/part-of: ingress-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-errors
        app.kubernetes.io/part-of: ingress-nginx
    spec:
        volumes:
          - name: volume-web-pages
            configMap:
                name: web-pages
        containers:
          - name: nginx-error-server
            image: quay.io/kubernetes-ingress-controller/custom-error-pages-amd64:0.4
            ports:
              - containerPort: 8080
            volumeMounts:
              - name: volume-web-pages
                mountPath: /www
            # Setting the environment variable DEBUG we can see the headers sent 
            # by the ingress controller to the backend in the client response.
            # env:
            # - name: DEBUG
            #   value: "true"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: web-pages
  #namespace: default
data:
    404.html: |-
        <!DOCTYPE html>
        <html lang="en">
          <head>
            <meta charset="utf-8">
            <title>title</title>
            <link rel="stylesheet" href="style.css">
            <script src="script.js"></script>
          </head>
          <body>
            <span>404.html : The page you're looking for could not be found.</span>
          </body>
        </html>

